### ISSUE TITLE
[Feature Request] Hotkeys for Sidebars Behavior (Hide/Show)

### ISSUE THREAD

**Issue by FelipeRearden** [phibr0/obsidian-customizable-sidebar#1]
Hello @phibr0 !!!

I'd like to make a feature request for Obsidian Customizable Sidebar 

I know that my request is not 100% to this plug-in but is 100% related to customizations to the sidebars 

My request is simple to explain: create Obsidian Commands (command palette) to `close/hide` and `show/open` the right and left sidebars. (more details above)

**Why I’m asking for these 2 last hotkeys... if Obsidian already have** `TOGGLE RIGHT SIDEBAR` and  `TOGGLE LEFT SIDEBAR`.

- These hotkeys open/close (show/hide) the depending on the present position: if it is open the hotkey closes and vice-versa
- For many workflows it's important to have just one behavior for each action.  

### Cenario
I use this 2 plugins a lot: Workspaces (core-plugin) and [Maximise Active Panel](https://github.com/deathau/maximise-active-pane-obsidian). I have a writing/reading workspace that is like this:
![img001](https://user-images.githubusercontent.com/85180696/129246068-7f550ce6-26ac-4579-92c1-c486d4e427c8.png)

When I toggle Maximise Active Panel, the active panel goes to full screen BUT the right sidebar and the left sidebar keeps open. Then I have to use two hotkeys to hide the the right sidebar and the left sidebar.

When I came back to the normal view I have again to press two hot key to get my 2 sidebars open again.

This just one example of other workflows that I have.

### FR Details 
In my opinion, we have 4 hotkeys for this:

`HIDE RIGHT SIDEBAR`

-   If the right sidebar is already **closed**, the hotkey **keeps the sidebar closed** when pressed.
-   The mission of the hotkey is always to close the sidebar

`HIDE LEFT SIDEBAR`

-   If the left sidebar is already **closed**, the hotkey **keeps the sidebar closed** when pressed.
-   The function of the hotkey is always to close the sidebar

`SHOW RIGHT SIDEBAR`

-   If the right sidebar is already **open**, the hotkey **keeps the sidebar open** when pressed.
-   The mission of the hotkey is always to open the sidebar

`SHOW LEFT SIDEBAR`

-   If the left sidebar is already **open**, the hotkey **keeps the sidebar open** when pressed.
-   The mission of the hotkey is always to open the sidebar

### A Powerfull Combo with Obsidian Macros
My ideia is to use this new hotkeys with your new plug-in [Obsidian Macros](https://github.com/phibr0/obsidian-macros) to create complex macros with many obsidian commands!!!!

- In my CENARIO, I could have a macro with MAXIMISE + HIDE RIGHT SIDEBAR AND HIDE LEFT SIDEBAR
- And other to came back to normal view: MAXIMISE + SHOW RIGHT SIDEBAR AND SHOW LEFT SIDEBAR

---

I really hope you like my suggestion. Sorry if it was a long text. I tried to explain the importance of this hotkeys for my workflow.

Let me know if you need clarification.

Thanks and have a great day!
Fun fact-> Philip means Felipe in Portuguese (we have the same name) :)

**Comment by phibr0** [comment]
I added the Commands to close and open both Sidebars respectively.

Thanks for your detailed Feature Request!

**Comment by FelipeRearden** [comment]
Hello @phibr0  !!!

Thank you very much for making this feature :) I'm so happy!!!

Just one little information: when I am installing the plug-in today I get this notification And I can't install the plug-in. Take a look:
![Screen Shot 2021-08-14 at 07 38 53](https://user-images.githubusercontent.com/85180696/129443796-32812811-afd5-4be0-b80b-b142aa205411.png)

**Comment by phibr0** [comment]
Thats weird. What Obsidian Version are you on?

**Comment by FelipeRearden** [comment]
> Thats weird. What Obsidian Version are you on?

Sorry I forgot to tell: Obsidian 0.12.10 on MacOS

**Comment by phibr0** [comment]
Why don't you update to 0.12.12? The Plugin requires you to have that Version.

**Comment by FelipeRearden** [comment]
Sorry @phibr0 !!!

My bad, I let automatic updates disable :( . Let me update right now and I get back to you in a few minutes

**Comment by FelipeRearden** [comment]
@phibr0 

Thank you so much !!! 100% working!!! 

Sorry for my mistake and thanks again for this new feature :) 

I wish you a fantastic weekend!!!

**Comment by phibr0** [comment]
Thanks, you too! 
Definitely not a must, but if you'd like you can support me here: https://buymeacoffee.com/phibr0
