### ISSUE TITLE
[Feature Request] Toggle command

### ISSUE THREAD

**Issue by Zebrazilla** [phibr0/obsidian-customizable-sidebar#2]
I would like to suggest a feature for adding buttons that toggle. One such use case would be to toggle between light and dark mode. 

Essentially the button would have the possibility of adding two commands and two icons, where the icon is switched when toggled and the associated command is fired. There could be more use cases other than toggling between theme modes, can't think of any right now however.

Thank you for an awesome plugin!

**Comment by phibr0** [comment]
I added the Toggle Command for the Theme

**Comment by Zebrazilla** [comment]
> I added the Toggle Command for the Theme

Great stuff!
