### ISSUE TITLE
Support arrange sidebar icons order

### ISSUE THREAD

**Issue by wenlzhang** [phibr0/obsidian-customizable-sidebar#4]
Is it possible to change the order of icons in the sidebar? As the number of sidebar icons increases, it would be great to be able to do this.

**Comment by NomarCub** [comment]
Unfortunately I can't rearrange existing icons with this. Which means that without [custom icons](https://github.com/phibr0/obsidian-customizable-sidebar/issues/12) I can't recreate the [VSCode](https://github.com/NomarCub/obsidian-open-vscode) ribbon icon and order it too.
