### ISSUE TITLE
No longer available on Obsidian Community plugins

### ISSUE THREAD

**Issue by jamie9090** [phibr0/obsidian-customizable-sidebar#5]
![image](https://user-images.githubusercontent.com/69635548/130339242-bcf54691-c4ef-4df8-a4a9-7c79e8e7588d.png)

Just an FYI!

**Comment by phibr0** [comment]
If you are referring to the Emoji Shortcodes Plugin, its not yet approved and thus not yet in the Plugin Browser. If you are referring to this Plugin it is there, its called "Customizable Sidebar"
