### ISSUE TITLE
[Enhancement] Edit Existing Command

### ISSUE THREAD

**Issue by ozntel** [phibr0/obsidian-customizable-sidebar#6]
Hi,
I like your plugin. It is really useful for the commands I use so often! 
Just throwing an idea as an enhancement. It would be great to be able to edit existing commands. 
Right now you need to delete the command, restart obsidian and create a new one even if you only want to change the icon.
Thanks!

**Comment by kzhovn** [comment]
@phibr0 I've implemented a version of icon editing in [Customizable Menu](https://github.com/kzhovn/obsidian-customizable-menu), which should be pretty quick for me to port over to Customizable Sidebar since it's mostly built on your code. Happy to make a PR if you're interested.

**Comment by phibr0** [comment]
That would be pretty cool!

**Comment by kzhovn** [comment]
I've made the change locally but apparently you can't have multiple forks of one repository (??), so I'm a little stuck on how to get it to you. If you invite me as a collaborator I can push the change on a new branch?

**Comment by phibr0** [comment]
I invited you! Go ahead if you are ready

**Comment by kzhovn** [comment]
Pushed https://github.com/phibr0/obsidian-customizable-sidebar/tree/icon_editing. I made a couple very minor unrelated edits (fixed a typo, set a couple words to lowercase that shouldn't be capitalized in standard English), but I'm happy to undo them if you want to be able to merge the branch without them.

**Comment by phibr0** [comment]
Thanks @kzhovn! Just published the new Release
